# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-08 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmq', '0004_user_rmq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_rmq',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='u_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='u_password',
        ),
        migrations.AlterModelTable(
            name='user',
            table='rmq_user',
        ),
    ]
