# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-08 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmq', '0006_auto_20180608_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='u_ticket',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
