# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-09 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmq', '0007_users_u_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_apply_rmq',
            name='rmq_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmq.Users'),
        ),
    ]
