# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-09 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmq', '0008_auto_20180609_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info_apply_rmq',
            old_name='rmq_user',
            new_name='users',
        ),
    ]
