# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-09 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmq', '0009_auto_20180609_1407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info_ip',
            new_name='Infoip',
        ),
        migrations.RenameField(
            model_name='info_apply_rmq',
            old_name='info_ip',
            new_name='infoip',
        ),
    ]
