# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-12 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmq', '0011_auto_20180609_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='u_email',
            field=models.CharField(default=True, max_length=25),
        ),
    ]
